(deftheme beakstar-bright
  "Created 2021-07-04.")

(custom-theme-set-variables
 'beakstar-bright
 '(frame-background-mode 'dark)
 '(ansi-color-names-vector '(vector "#000000" "#d54e53" "#b9ca4a" "#e7c547" "#7aa6da" "#c397d8" "#70c0b1" "#eaeaea"))
 '(ansi-color-faces-vector [default bold shadow italic underline bold bold-italic bold])
 '(window-divider-mode nil))

(custom-theme-set-faces
 'beakstar-bright
 '(bold ((((class color) (min-colors 89)) (:weight bold))))
 '(bold-italic ((((class color) (min-colors 89)) (:slant italic :weight bold))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(italic ((((class color) (min-colors 89)) (:slant italic))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#969896" :slant italic))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#969896" :slant italic))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#d54e53"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(fill-column-indicator ((((class color) (min-colors 89)) (:foreground "#424242" :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil))))
 '(success ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(tooltip ((((class color) (min-colors 89)) (:foreground "#e7c547" :background "#000000" :inverse-video t))))
 '(cursor ((((class color) (min-colors 89)) (:background "#d54e53"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#151515151515" :foreground "#969896"))))
 '(line-number ((((class color) (min-colors 89)) (:background "#151515151515" :foreground "#969896"))))
 '(line-number-current-line ((((class color) (min-colors 89)) (:inherit line-number :foreground "#eaeaea" :weight bold))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#424242"))))
 '(border ((((class color) (min-colors 89)) (:background "#424242" :foreground "#2a2a2a"))))
 '(highlight ((((class color) (min-colors 89)) (:inverse-video nil :background "#2a2a2a"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#eaeaea" :background "#424242" :weight normal :box (:line-width 1 :color "#424242")))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#c397d8" :background unspecified))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#969896" :background "#2a2a2a" :weight normal))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:foreground "#eaeaea" :slant italic))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "#c397d8" :box nil :weight bold))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(region ((((class color) (min-colors 89)) (:background "#424242" :inverse-video nil :extend t))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#2a2a2a" :extend t))))
 '(header-line ((((class color) (min-colors 89)) (:inherit mode-line-inactive :foreground "#70c0b1" :background unspecified))))
 '(match ((((class color) (min-colors 89)) (:foreground "#7aa6da" :background "#000000" :inverse-video t))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#e7c547" :background "#000000" :inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#70c0b1" :background "#000000" :inverse-video t))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#000000" :inherit font-lock-warning-face :inverse-video t))))
 '(link ((((class color) (min-colors 89)) (:foreground unspecified :underline t))))
 '(widget-button ((((class color) (min-colors 89)) (:underline t))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#424242" :box (:line-width 1 :color "#eaeaea")))))
 '(diary ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(holiday ((((class color) (min-colors 89)) (:foreground "#000000" :background "#e78c45"))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(completions-annotations ((((class color) (min-colors 89)) (:foreground "#969896" :slant italic))))
 '(completions-common-part ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(completions-first-difference ((((class color) (min-colors 89)) (:foreground "#e78c45" :weight bold))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :weight bold))))
 '(flycheck-error ((((class color) (min-colors 89)) (:underline (:style wave :color "#d54e53")))))
 '(flycheck-info ((((class color) (min-colors 89)) (:underline (:style wave :color "#70c0b1")))))
 '(flycheck-warning ((((class color) (min-colors 89)) (:underline (:style wave :color "#e78c45")))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(flyspell-incorrect ((((class color) (min-colors 89)) (:underline (:style wave :color "#d54e53")))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground unspecified :background unspecified :weight normal))))
 '(message-header-subject ((((class color) (min-colors 89)) (:inherit message-header-other :weight bold :foreground "#e7c547"))))
 '(message-header-to ((((class color) (min-colors 89)) (:inherit message-header-other :weight bold :foreground "#e78c45"))))
 '(message-header-cc ((((class color) (min-colors 89)) (:inherit message-header-to :foreground unspecified))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#7aa6da" :background unspecified))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#70c0b1" :background unspecified :slant normal))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(+org-todo-onhold ((((class color) (min-colors 89)) (:foreground "#8c8e4e"))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(org-agenda-current-time ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#7aa6da" :underline nil))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(org-block ((((class color) (min-colors 89)) (:font "Input Mono Narrow" :background "#151515151515"))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:background "#000000" :foreground "#969896" :slant italic))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:background "#000000" :foreground "#969896" :slant italic))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#424242"))))
 '(org-column-title ((((class color) (min-colors 89)) (:inherit org-column :weight bold :underline t))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "dim gray" :underline t))))
 '(org-date-selected ((((class color) (min-colors 89)) (:foreground "#70c0b1" :inverse-video t))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(org-document-title ((((class color) (min-colors 89)) (:weight bold :foreground "#e78c45" :height 1.4))))
 '(org-done ((((class color) (min-colors 89)) (:foreground "#247a6c"))))
 '(org-drawer ((((class color) (min-colors 89)) (:foreground "#9fb6cd" :height 0.7))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(org-formula ((((class color) (min-colors 89)) (:font "Input Mono Narrow" :foreground "#d54e53"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:foreground "LightSteelBlue4"))))
 '(org-headline-todo ((((class color) (min-colors 89)) (:foreground "LightSteelBlue3"))))
 '(org-hide ((((class color) (min-colors 89)) (:font "Input Mono" :foreground "#000000" :background "#000000" :height 1.0))))
 '(org-indent ((((class color) (min-colors 89)) (:font "Input Mono" :foreground "#000000" :background "#000000")))) ;; Same as hide - for some reason it's different if I just inherit it. Maybe due to the relative size in the default font?
 '(org-link ((((class color) (min-colors 89)) (:foreground "#7aa6da" :underline t))))
 '(org-meta-line ((((class color) (min-colors 89)) (:inherit 'font-lock-comment-face :height 0.7))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:inherit mode-line :background "#d54e53"))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(org-table ((((class color) (min-colors 89)) (:font "Input Mono Narrow" :foreground "#c397d8"))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#a14962"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(org-warning ((((class color) (min-colors 89)) (:weight bold :foreground "#d54e53"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:inherit 'outline-1 :height 1.0 :foreground "#e0c341"))))
 '(org-level-4 ((((class color) (min-colors 89)) (:inherit 'outline-2 :height 1.0 :foreground "#6a50a7"))))
 '(org-level-3 ((((class color) (min-colors 89)) (:inherit 'outline-3 :height 1.0 :foreground "#bf263c"))))
 '(org-level-2 ((((class color) (min-colors 89)) (:inherit 'outline-4 :height 1.0 :foreground "#7db1b1"))))
 ;; '(org-level-1 ((((class color) (min-colors 89)) (:inherit 'outline-1 :height 1.0)))""")
 ;; '(org-level-2 ((((class color) (min-colors 89)) (:inherit 'outline-2 :height 1.0))))
 ;; '(org-level-3 ((((class color) (min-colors 89)) (:inherit 'outline-3 :height 1.0))))
 ;; '(org-level-4 ((((class color) (min-colors 89)) (:inherit 'outline-4 :height 1.0))))
 '(org-level-5 ((((class color) (min-colors 89)) (:inherit 'outline-5 :height 1.0))))
 '(org-level-6 ((((class color) (min-colors 89)) (:inherit 'outline-6 :height 1.0))))
 '(org-level-7 ((((class color) (min-colors 89)) (:inherit 'outline-7 :height 1.0))))
 '(org-level-8 ((((class color) (min-colors 89)) (:inherit 'outline-8 :height 1.0))))
 '(org-default ((((class color) (min-colors 89)) (:inherit default :foreground "#bebebe" :font "Input Sans Narrow" :height 1.1))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit nil :foreground "#7aa6da"))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit nil :foreground "#c397d8"))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit nil :foreground "#70c0b1"))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit nil :foreground "#e7c547"))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit nil :foreground "#e78c45"))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit nil :foreground "#7aa6da"))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit nil :foreground "#c397d8"))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit nil :foreground "#70c0b1"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "#c397d8" :foreground "#000000"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:background "#d54e53" :foreground "#000000"))))
 '(speedbar-button-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(speedbar-directory-face ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(speedbar-file-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(speedbar-highlight-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(speedbar-selected-face ((((class color) (min-colors 89)) (:foreground "#d54e53" :underline t))))
 '(speedbar-separator-face ((((class color) (min-colors 89)) (:foreground "#000000" :background "#7aa6da" :overline "#000000"))))
 '(speedbar-tag-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(tab-bar ((((class color) (min-colors 89)) (:height 1.2 :foreground "#969896" :background "#2a2a2a"))))
 '(tab-bar-tab ((((class color) (min-colors 89)) (:background "#424242" :foreground "#c397d8" :inverse-video nil :box (:line-width 1 :style released-button)))))
 '(tab-bar-tab-inactive ((((class color) (min-colors 89)) (:inherit tab-bar-tab :background "#969896" :foreground "#2a2a2a" :inverse-video t))))
 '(tab-line ((((class color) (min-colors 89)) (:foreground "#969896" :background "#2a2a2a"))))
 '(whitespace-big-indent ((((class color) (min-colors 89)) (:background "#d54e53" :foreground "#424242"))))
 '(whitespace-empty ((((class color) (min-colors 89)) (:background "#e7c547" :foreground "#e78c45"))))
 '(whitespace-hspace ((((class color) (min-colors 89)) (:background "#424242" :foreground "#969896"))))
 '(whitespace-indentation ((((class color) (min-colors 89)) (:background "#424242" :foreground "#969896"))))
 '(whitespace-line ((((class color) (min-colors 89)) (:background "#424242" :foreground "#e78c45"))))
 '(whitespace-newline ((((class color) (min-colors 89)) (:background "#424242" :foreground "#969896"))))
 '(whitespace-space ((((class color) (min-colors 89)) (:background "#424242" :foreground "#969896"))))
 '(whitespace-space-after-tab ((((class color) (min-colors 89)) (:background "#424242" :foreground "#e7c547"))))
 '(whitespace-space-before-tab ((((class color) (min-colors 89)) (:background "#424242" :foreground "#e78c45"))))
 '(whitespace-tab ((((class color) (min-colors 89)) (:background "#424242" :foreground "#969896"))))
 '(whitespace-trailing ((((class color) (min-colors 89)) (:background "#e78c45" :foreground "#424242"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:inherit whitespace-trailing))))
 '(window-divider ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(window-divider-first-pixel ((((class color) (min-colors 89)) (:foreground "#424242"))))
 '(window-divider-last-pixel ((((class color) (min-colors 89)) (:foreground "#424242"))))
 '(avy-background-face ((((class color) (min-colors 89)) (:foreground "#424242"))))
 '(avy-lead-face ((((class color) (min-colors 89)) (:foreground "#000000" :background "#e7c547"))))
 '(avy-lead-face-0 ((((class color) (min-colors 89)) (:foreground "#000000" :background "#7aa6da"))))
 '(avy-lead-face-1 ((((class color) (min-colors 89)) (:foreground "#000000" :background "#70c0b1"))))
 '(avy-lead-face-2 ((((class color) (min-colors 89)) (:foreground "#000000" :background "#e78c45"))))
 '(company-preview ((((class color) (min-colors 89)) (:foreground "#969896" :background "#424242"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:inherit company-preview :foreground "#d54e53"))))
 '(company-preview-search ((((class color) (min-colors 89)) (:inherit company-preview :foreground "#7aa6da"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#424242"))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:foreground "#969896" :inverse-video t))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:inherit company-tooltip :foreground "#d54e53"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:inherit company-tooltip-selection :foreground "#d54e53"))))
 '(company-tooltip-search ((((class color) (min-colors 89)) (:inherit company-tooltip :foreground "#7aa6da"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:inherit company-tooltip :foreground "#b9ca4a"))))
 '(company-tooltip-annotation-selection ((((class color) (min-colors 89)) (:inherit company-tooltip-selection :foreground "#b9ca4a"))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:inherit 'company-tooltip :background "#2a2a2a"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#424242"))))
 '(company-echo-common ((((class color) (min-colors 89)) (:inherit company-echo :foreground "#d54e53"))))
 '(diredp-compressed-file-suffix ((((class color) (min-colors 89)) (:inherit diredfl-compressed-file-suffix))))
 '(diredp-compressed-file-name ((((class color) (min-colors 89)) (:inherit diredfl-compressed-file-name))))
 '(diredp-deletion ((((class color) (min-colors 89)) (:inherit diredfl-deletion))))
 '(diredp-deletion-file-name ((((class color) (min-colors 89)) (:inherit diredfl-deletion-file-name))))
 '(diredp-date-time ((((class color) (min-colors 89)) (:inherit diredfl-date-time))))
 '(diredp-dir-heading ((((class color) (min-colors 89)) (:inherit diredfl-dir-heading))))
 '(diredp-dir-name ((((class color) (min-colors 89)) (:inherit diredfl-dir-name))))
 '(diredp-dir-priv ((((class color) (min-colors 89)) (:inherit diredfl-dir-priv))))
 '(diredp-exec-priv ((((class color) (min-colors 89)) (:inherit diredfl-exec-priv))))
 '(diredp-executable-tag ((((class color) (min-colors 89)) (:inherit diredfl-executable-tag))))
 '(diredp-file-name ((((class color) (min-colors 89)) (:inherit diredfl-file-name))))
 '(diredp-file-suffix ((((class color) (min-colors 89)) (:inherit diredfl-file-suffix))))
 '(diredp-flag-mark ((((class color) (min-colors 89)) (:inherit diredfl-flag-mark))))
 '(diredp-flag-mark-line ((((class color) (min-colors 89)) (:inherit diredfl-flag-mark-line))))
 '(diredp-ignored-file-name ((((class color) (min-colors 89)) (:inherit diredfl-ignored-file-name))))
 '(diredp-link-priv ((((class color) (min-colors 89)) (:inherit diredfl-link-priv))))
 '(diredp-mode-line-flagged ((((class color) (min-colors 89)) (:inherit diredfl-mode-line-flagged))))
 '(diredp-mode-line-marked ((((class color) (min-colors 89)) (:inherit diredfl-mode-line-marked))))
 '(diredp-no-priv ((((class color) (min-colors 89)) (:inherit diredfl-no-priv))))
 '(diredp-number ((((class color) (min-colors 89)) (:inherit diredfl-number))))
 '(diredp-other-priv ((((class color) (min-colors 89)) (:inherit diredfl-other-priv))))
 '(diredp-rare-priv ((((class color) (min-colors 89)) (:inherit diredfl-rare-priv))))
 '(diredp-read-priv ((((class color) (min-colors 89)) (:inherit diredfl-read-priv))))
 '(diredp-symlink ((((class color) (min-colors 89)) (:inherit diredfl-symlink))))
 '(diredp-write-priv ((((class color) (min-colors 89)) (:inherit diredfl-write-priv))))
 '(hydra-face-blue ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(hydra-face-teal ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(hydra-face-pink ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(hydra-face-red ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(hydra-face-amaranth ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(ivy-action ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(ivy-confirm-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(ivy-current-match ((((class color) (min-colors 89)) (:background "#424242"))))
 '(ivy-cursor ((((class color) (min-colors 89)) (:background "#424242"))))
 '(ivy-match-required-face ((((class color) (min-colors 89)) (:foreground "#d54e53" :background "#000000"))))
 '(ivy-remote ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(ivy-subdir ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(ivy-virtual ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(ivy-minibuffer-match-face-1 ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(ivy-minibuffer-match-face-2 ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(ivy-minibuffer-match-face-3 ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(ivy-minibuffer-match-face-4 ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(pulse-highlight-start-face ((((class color) (min-colors 89)) (:background "#d54e53"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#eaeaea"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#eaeaea"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(sp-show-pair-match-face ((((class color) (min-colors 89)) (:foreground unspecified :background unspecified :inherit show-paren-match))))
 '(sp-show-pair-mismatch-face ((((class color) (min-colors 89)) (:foreground unspecified :background unspecified :inherit show-paren-mismatch))))
 '(swiper-line-face ((((class color) (min-colors 89)) (:underline t))))
 '(transient-enabled-suffix ((((class color) (min-colors 89)) (:foreground "#151515151515" :background "#b9ca4a" :weight bold))))
 '(transient-disabled-suffix ((((class color) (min-colors 89)) (:foreground "#eaeaea" :background "#d54e53" :weight bold))))
 ;; '(default ((((class color) (min-colors 89)) (:foreground "#eaeaea" :background "#000000"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#000000" :height 150))))
 '(doom-modeline-evil-insert-state ((((class color) (min-colors 89)) (:foreground "#ff292d"))))
 '(doom-modeline-evil-normal-state ((((class color) (min-colors 89)) (:foreground "#0BF200"))))
 '(doom-modeline-evil-visual-state ((((class color) (min-colors 89)) (:foreground "#ff9400"))))
 '(doom-dashboard-banner ((((class color) (min-colors 89)) (:foreground "#D6C59A"))))
 '(doom-dashboard-menu-desc ((((class color) (min-colors 89)) (:foreground "#E27638"))))
 '(doom-dashboard-menu-title ((((class color) (min-colors 89)) (:foreground "#8B4014")))))

(provide-theme 'beakstar-bright)
